### PR TITLE
perfs: negative pow exponent

### PR DESCRIPTION
**Pull request by oliverlj**
I don't know how to run the bench,. Maybe you add a line in scripts package.json ?

### CODE REVIEW

**Comment by evert** [comment]
Hi @oliverlj ,

While your PR makes the operation a bit shorter, I don't think it's going to be any faster, because it's effectively the same algorithm, except it's now recursive. So, I feel that the original is a bit simpler (despite having a bit more code).

A more effective way to implement this, that's potentially a bit faster is to operate on the underlying `bigint` instead of Money objects until the operation is "complete", just like the positive exponent version is doing.

**Comment by oliverlj** [comment]
this is why I would like to bench :)

What I did use ** for negative exponent, so it should be optimized with a complexity lower than o(n) ?

**Comment by evert** [comment]
Yeah if you'd like to test the benchmarks, it might need some little modifications to make them work. I think bench.js just expects `bigint-money` and another lib to exists in a local node_modules. Maybe we just need a package.json in the bench directory to get that to work? Shouldn't be too hard to get that going.

**Comment by evert** [comment]
I just realized that your solution is way smarter than I thought. Yours does indeed seem better! I thought you were just calling `.pow()` recursively reducing the exponent by `-1` every time, but I misread. I'm ok merging this now, but also happy to wait for a benchmark first. Lemme know!

**Comment by oliverlj** [comment]
Thanks ! I still used the lib a lot

**Comment by evert** [comment]
Sorry for the wait =)

**Pull request merged**
